####################################################################################
##               ,:                                                         ,:    ##
##             ,' |                                                       ,' |    ##
##            /   :                                                      /   :    ##
##         --'   /       :::::::::::   :::::::::::   :::    :::       --'   /     ##
##         \/ />/           :+:            :+:       :+:   :+:        \/ />/      ##
##         / /_\           +:+            +:+       +:+  +:+          / /_\       ##
##      __/   /           +#+            +#+       +#++:++         __/   /        ##
##      )'-. /           +#+            +#+       +#+  +#+         )'-. /         ##
##      ./  :\          #+#        #+# #+#       #+#   #+#         ./  :\         ##
##       /.' '         ###         #####        ###    ###          /.' '         ##
##     '/'                                                        '/'             ##
##     +                                                          +               ##
##    '                                                          '                ##
####################################################################################
##            Copyright © 2023 Tyler J. Kenney. All rights reserved.              ##
####################################################################################
####################################################################################

## NOTICE: DO NOT EDIT!!
## NOTICE: This file was autogenerated by gen-mod-pipelines.py
## NOTICE: DO NOT EDIT!!


## Sub-Pipeline: tf_to_mo
export tf_to_mo="builtin.module(
tf-to-mo{prune-assert-ops=true use-mo-ops=true},
cse,
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true}
)"


## Sub-Pipeline: shape_inference
export shape_inference="builtin.module(
resolve-unknown-parameters,
materialize-shape-funcs,
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
staticize-shapes,
inline-shape-funcs,
cse,
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
symbol-dce,
mo.graph(propagate-shapes),
cse,
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
mo.graph(symbolic-optimize),
mo.graph(propagate-shapes),
mo.graph(add-fallback-shape-funcs),
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
cse,
mo.graph(symbolic-optimize),
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
cse,
mo.graph(lower-qdq-operators-to-mo{fixup-dtypes=true lower-computational-ops=true}),
mo.graph(legalize-moq-ops-to-mo),
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
cse,
resolve-unknown-parameters,
materialize-shape-funcs,
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
staticize-shapes,
inline-shape-funcs,
cse,
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
symbol-dce,
mo.graph(propagate-shapes),
cse,
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
mo.graph(symbolic-optimize),
mo.graph(propagate-shapes),
mo.graph(add-fallback-shape-funcs),
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
cse,
mo.graph(symbolic-optimize),
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
cse,
mo.graph(add-devices{enable-extra-devices=false}),
mo.graph(assign-devices)
)"


## Sub-Pipeline: mo_to_mogg
export mo_to_mogg="builtin.module(
mo.graph(infer-layouts),
mo.graph(mo-pattern-fusion),
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
cse,
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
cse,
mo.graph(hoist-param-exprs),
mo-to-mogg{extra-lib-paths=},
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
cse
)"


## Sub-Pipeline: mo_fusion
export mo_fusion="builtin.module(
mo.graph(fuse-elementwise{dump-dot-graph=false}),
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
cse,
mo.graph(fuse-bcasts),
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
cse,
mo.graph(fuse-in-out-lambdas),
cse,
mo.graph(mark-trivial-kernels),
mo.graph(inline-lambdas),
mo.graph(soft-fuse),
mo.graph(add-explicit-chain-ready),
mo.graph(fuse-consts),
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
cse
)"


## Sub-Pipeline: mogg_to_mgp
export mogg_to_mgp="builtin.module(
jit-compile-kernels{create-mogg-reproducers=false dump-stub=false extra-lib-paths= min-cpu-alignment=16 save-temp-prefix= use-search=false},
mo-to-primitives{compiled-framework-label=mof min-cpu-alignment=16},
cse,
remove-redundant-tensor-extracts,
mgp.model(simplify-chains),
mgp.model(concat-in-place),
mgp.model(defer-allocs),
mgp.model(exec-invariant-code-motion),
mgp.model(predicate-asserts-deps),
mgp.model(strip-buffer-attributes),
canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=true test-convergence=false top-down=true},
mgp.model(simplify-chains),
cse
)"
